# Mint Custom Theme Settings

# 导航栏设置
header_bg_color:
  default: "#3B66F5"
  type: string
  description: "导航栏背景颜色"

header_text_color:
  default: "#ffffff"
  type: string
  description: "导航栏文字颜色"

header_height:
  default: "3.5em"
  type: string
  description: "导航栏高度"
